name: Deploy slides and Julia docs

on:
  push:
    branches:
      - main
    paths:
      - 'julia/**'
      - '.github/workflows/deploy.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'julia/**'

jobs:
  docs:
    name: Deploy slides and Julia docs
    runs-on: ubuntu-latest
    permissions:
      contents: write
      statuses: write
    steps:
      - uses: actions/checkout@v4
      
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1.11'
      
      - uses: julia-actions/cache@v1
      
      - name: Configure git
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
      
      - name: Install dependencies
        run: |
          # Only install docs dependencies (Documenter.jl)
          julia --project=julia/docs -e 'using Pkg; Pkg.instantiate()'
          # Add the local package for docstring extraction only
          julia --project=julia/docs -e 'using Pkg; Pkg.develop(PackageSpec(path="julia"))'
      
      - name: Build docs
        run: |
          cd julia/docs
          julia --project=. make.jl
          
      - name: Save built docs
        run: |
          # Copy built docs using absolute path
          if cp -r julia/docs/build /tmp/docs-build; then
            echo "✅ Successfully copied built docs to /tmp/docs-build"
            echo "Contents of /tmp/docs-build:"
            ls -la /tmp/docs-build/
          else
            echo "❌ Failed to copy built docs"
            echo "Checking if julia/docs/build exists:"
            ls -la julia/docs/build/ || echo "julia/docs/build directory does not exist"
            exit 1
          fi
      
      - name: Deploy to gh-pages
        run: |
          # Copy main branch content to gh-pages (for RevealJS)
          git checkout --orphan gh-pages-temp
          git rm -rf .
          
          # Copy all main branch files except .git
          git checkout main -- .
          
          # Remove julia/docs/build if it exists (we'll add fresh one)
          rm -rf julia/docs/build
          
          # Copy built docs from the previous step
          mkdir -p julia/docs/build
          if cp -r /tmp/docs-build/* julia/docs/build/; then
            echo "✅ Successfully copied docs to julia/docs/build"
            echo "Contents of julia/docs/build:"
            ls -la julia/docs/build/
          else
            echo "❌ Failed to copy docs to julia/docs/build"
            exit 1
          fi
          
          # Configure git and commit
          git config user.email "action@github.com"
          git config user.name "GitHub Action"
          
          # Debug: Check what's actually there before git add
          echo "=== Files in julia/docs/build before git add ==="
          ls -la julia/docs/build/ || echo "Directory missing"
          
          # Check if .gitignore is blocking build directories
          echo "=== Checking .gitignore ==="
          cat .gitignore | grep -i build || echo "No build rules in .gitignore"
          
          git add .
          
          # Debug: What did git actually stage?
          echo "=== Git status after git add ==="
          git status --porcelain
          
          # Force add build directory (ignore .gitignore)
          git add julia/docs/build/ --force
          
          git commit -m "Deploy slides and Julia docs"
          
          # Force push to gh-pages
          git push -f origin gh-pages-temp:gh-pages
