name: Code Documentation

on:
  push:
    branches:
      - main
    paths:
      - 'julia/**'
      - '.github/workflows/docs.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'julia/**'

jobs:
  docs:
    name: Documentation
    runs-on: ubuntu-latest
    permissions:
      contents: write
      statuses: write
    steps:
      - uses: actions/checkout@v4
      
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1.10'
      
      - uses: julia-actions/cache@v1
      
      - name: Configure git
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
      
      - name: Install dependencies
        run: |
          julia --project=julia -e 'using Pkg; Pkg.instantiate()'
          julia --project=julia/docs -e 'using Pkg; Pkg.instantiate()'
      
      - name: Build and deploy docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          julia --project=julia/docs julia/docs/make.jl
